// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.5
// source: wallet/v1/wallet.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Wallet_GetBalance_FullMethodName      = "/wallet.v1.Wallet/GetBalance"
	Wallet_SendTransaction_FullMethodName = "/wallet.v1.Wallet/SendTransaction"
	Wallet_SuggestGasPrice_FullMethodName = "/wallet.v1.Wallet/SuggestGasPrice"
	Wallet_TxCost_FullMethodName          = "/wallet.v1.Wallet/TxCost"
	Wallet_DepositWallet_FullMethodName   = "/wallet.v1.Wallet/DepositWallet"
	Wallet_WithdrawWallet_FullMethodName  = "/wallet.v1.Wallet/WithdrawWallet"
)

// WalletClient is the client API for Wallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletClient interface {
	GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceReply, error)
	SendTransaction(ctx context.Context, in *TxRequest, opts ...grpc.CallOption) (*TxReply, error)
	SuggestGasPrice(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GasPrice, error)
	TxCost(ctx context.Context, in *TxCostRequest, opts ...grpc.CallOption) (*TxCostReply, error)
	DepositWallet(ctx context.Context, in *Deposit, opts ...grpc.CallOption) (*DepositResult, error)
	WithdrawWallet(ctx context.Context, in *Withdrawal, opts ...grpc.CallOption) (*WithdrawalResult, error)
}

type walletClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletClient(cc grpc.ClientConnInterface) WalletClient {
	return &walletClient{cc}
}

func (c *walletClient) GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceReply, error) {
	out := new(BalanceReply)
	err := c.cc.Invoke(ctx, Wallet_GetBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) SendTransaction(ctx context.Context, in *TxRequest, opts ...grpc.CallOption) (*TxReply, error) {
	out := new(TxReply)
	err := c.cc.Invoke(ctx, Wallet_SendTransaction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) SuggestGasPrice(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GasPrice, error) {
	out := new(GasPrice)
	err := c.cc.Invoke(ctx, Wallet_SuggestGasPrice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) TxCost(ctx context.Context, in *TxCostRequest, opts ...grpc.CallOption) (*TxCostReply, error) {
	out := new(TxCostReply)
	err := c.cc.Invoke(ctx, Wallet_TxCost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) DepositWallet(ctx context.Context, in *Deposit, opts ...grpc.CallOption) (*DepositResult, error) {
	out := new(DepositResult)
	err := c.cc.Invoke(ctx, Wallet_DepositWallet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) WithdrawWallet(ctx context.Context, in *Withdrawal, opts ...grpc.CallOption) (*WithdrawalResult, error) {
	out := new(WithdrawalResult)
	err := c.cc.Invoke(ctx, Wallet_WithdrawWallet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServer is the server API for Wallet service.
// All implementations must embed UnimplementedWalletServer
// for forward compatibility
type WalletServer interface {
	GetBalance(context.Context, *BalanceRequest) (*BalanceReply, error)
	SendTransaction(context.Context, *TxRequest) (*TxReply, error)
	SuggestGasPrice(context.Context, *Empty) (*GasPrice, error)
	TxCost(context.Context, *TxCostRequest) (*TxCostReply, error)
	DepositWallet(context.Context, *Deposit) (*DepositResult, error)
	WithdrawWallet(context.Context, *Withdrawal) (*WithdrawalResult, error)
	mustEmbedUnimplementedWalletServer()
}

// UnimplementedWalletServer must be embedded to have forward compatible implementations.
type UnimplementedWalletServer struct {
}

func (UnimplementedWalletServer) GetBalance(context.Context, *BalanceRequest) (*BalanceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedWalletServer) SendTransaction(context.Context, *TxRequest) (*TxReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTransaction not implemented")
}
func (UnimplementedWalletServer) SuggestGasPrice(context.Context, *Empty) (*GasPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuggestGasPrice not implemented")
}
func (UnimplementedWalletServer) TxCost(context.Context, *TxCostRequest) (*TxCostReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TxCost not implemented")
}
func (UnimplementedWalletServer) DepositWallet(context.Context, *Deposit) (*DepositResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositWallet not implemented")
}
func (UnimplementedWalletServer) WithdrawWallet(context.Context, *Withdrawal) (*WithdrawalResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawWallet not implemented")
}
func (UnimplementedWalletServer) mustEmbedUnimplementedWalletServer() {}

// UnsafeWalletServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServer will
// result in compilation errors.
type UnsafeWalletServer interface {
	mustEmbedUnimplementedWalletServer()
}

func RegisterWalletServer(s grpc.ServiceRegistrar, srv WalletServer) {
	s.RegisterService(&Wallet_ServiceDesc, srv)
}

func _Wallet_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Wallet_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GetBalance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_SendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).SendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Wallet_SendTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).SendTransaction(ctx, req.(*TxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_SuggestGasPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).SuggestGasPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Wallet_SuggestGasPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).SuggestGasPrice(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_TxCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxCostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).TxCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Wallet_TxCost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).TxCost(ctx, req.(*TxCostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_DepositWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Deposit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).DepositWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Wallet_DepositWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).DepositWallet(ctx, req.(*Deposit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_WithdrawWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Withdrawal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).WithdrawWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Wallet_WithdrawWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).WithdrawWallet(ctx, req.(*Withdrawal))
	}
	return interceptor(ctx, in, info, handler)
}

// Wallet_ServiceDesc is the grpc.ServiceDesc for Wallet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Wallet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.v1.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalance",
			Handler:    _Wallet_GetBalance_Handler,
		},
		{
			MethodName: "SendTransaction",
			Handler:    _Wallet_SendTransaction_Handler,
		},
		{
			MethodName: "SuggestGasPrice",
			Handler:    _Wallet_SuggestGasPrice_Handler,
		},
		{
			MethodName: "TxCost",
			Handler:    _Wallet_TxCost_Handler,
		},
		{
			MethodName: "DepositWallet",
			Handler:    _Wallet_DepositWallet_Handler,
		},
		{
			MethodName: "WithdrawWallet",
			Handler:    _Wallet_WithdrawWallet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet/v1/wallet.proto",
}
