// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/harrison-minibucks/gethelp/internal/biz"
	"github.com/harrison-minibucks/gethelp/internal/client"
	"github.com/harrison-minibucks/gethelp/internal/conf"
	"github.com/harrison-minibucks/gethelp/internal/data"
	"github.com/harrison-minibucks/gethelp/internal/server"
	"github.com/harrison-minibucks/gethelp/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, config *conf.Config, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	keystoreRepo := data.NewKeystoreRepo(config)
	ethclientClient := client.NewEthClient(config)
	walletUsecase := biz.NewWalletUsecase(keystoreRepo, logger, ethclientClient)
	walletService := service.NewWalletService(walletUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, walletService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, walletService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
